// bibliotecas | library
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>

// constantes globais | global constants
#define T 33
#define C 450

// structs globais | global structs
struct Tjogador {
	int id;
	int personagem;
	int posicao;
	int imagem;
};
struct Tcartas {
	int vantagem;
	int desvantagem;
	char tipo [C];
	char dica [C];
	char pergunta [C];
	char certa[C];
	int resposta;
	char certo1[C];
	char certo2[C];
	char errado1[C];
	char errado2[C];
	
};

// variaveis globais | global variables
int tabul[T][6];
int i;
int j;
struct Tjogador jogador[4];
int fim;
int qtd;
struct Tcartas carta [49];
int extra;

// funcoes | functions
int capa (int x);
int tabuleiro (int x);
int inicio (int x);
int peca (int a, int b, int c, int d, int e);
int cabecalho (int x, int y);
int jogadores (int x);
int personagens (int x);
int historia (int x);
int movimento (int x);
int dado (int x);
int cor (int x);
int turno (int x);
int perguntas (int x, int y);
int cartas (int x);
int aleatorio (int x);

// funcao principal | main function
int main (void) {
	int y;
	
	capa (y);
	
	historia (y);
	
	qtd = jogadores (y);
	
	personagens (y);
	
	inicio (y);
	
	turno (y);
	
	capa (y);	

	return 0;
}

// funcao que define o turno do jogador | function that defines the player's turn
int turno (int x) {
	int y, rodada=1, valordado, posicaoanterior;

	while (fim==0) {
	
		for (int vez=0;vez<qtd;vez++){
			cor (jogador[vez].personagem);
			
			cabecalho (vez, rodada);
	
			movimento (y);
	
			tabuleiro (y);
			
			if (jogador[vez].posicao < 32) {
						
				valordado = dado (y);
				
				tabul[jogador[vez].posicao][vez+1] = 0;
				
				jogador[vez].posicao = jogador[vez].posicao + valordado;
				
				if (jogador[vez].posicao > 31) {
					jogador[vez].posicao = 32;
				}
				
				cabecalho (vez, rodada);
				
				movimento (y);
		
				tabuleiro (y);
			}
			
			printf ("\n\n Obter Evento:\n [1] Sim \n Resposta: ");
			scanf ("%d", &y);
			y = 0;
			system ("cls");
			
			cabecalho (vez, rodada);
			
			extra = perguntas (jogador[vez].personagem, jogador[vez].posicao);
			
			if (extra == 4) {
				extra = 0;
				fim = 1;
			}
			
			tabul[jogador[vez].posicao][vez+1] = 0;
			
			jogador[vez].posicao = jogador[vez].posicao + extra;
			
			if (jogador[vez].posicao > 31) {
				jogador[vez].posicao = 32;
			}
			
			cabecalho (vez, rodada);
			
			movimento (y);
	
			tabuleiro (y);
			
			printf ("\n\n ----------\n ");
			system ("pause");
			system ("cls");
			
			if (fim == 1) {
				break;
			}
			
		}
		rodada ++;
	}
	return 0;
}

// funcao que define dados no incio do jogo | function that sets data at the beginning of the game
int inicio (int x) {
	fim = 0;
	
	cartas (0);
	
	for (i=0;i<T;i++) {
		tabul[i][0] = 176;
		for (j=1;j<5;j++){
			tabul[i][j] = 0;	
		}	
	}
	
	for (i=0;i<qtd;i++){
		jogador[i].posicao = 0;
		switch (jogador[i].personagem) {
			case 1: 
				jogador[i].imagem = 68; // Druida
				break;
			case 2:
				jogador[i].imagem = 66; // Bardo
				break;
			case 3:
				jogador[i].imagem = 71; // Guerreiro
				break;	
			case 4:
				jogador[i].imagem = 76; // Ladino
				break;
			default:
				jogador[i].imagem = 0; 
				break;
		}
	}
	
	return 0;
}

// funcao que define a movimentacao do jogador | function that defines the player's movement
int movimento (int x) {
	for (i=0;i<qtd;i++){
		tabul[jogador[i].posicao][i+1] = jogador[i].imagem;
	}
	return 0;	
}

// funcao que define o valor gerado pelo dado | function that defines the value generated by the data
int dado (int x) {
	srand (time(NULL));
	int y, resp;
	printf ("\n\n Rolar Dado:\n [1] Sim \n Resposta: ");
	scanf ("%d", &resp);
	y = 1 + rand()%(6);
	printf ("\n Valor Obtido: %d", y);
	printf ("\n\n ----------\n ");
	system ("pause");
	system ("cls");
	return y;
}

// funcao que imprime na tela o tabuleiro | function that prints the board on the screen
int tabuleiro (int x) {
	
	for (i=0;i<T;i++) {
		tabul[i][5]	= peca(tabul[i][0], tabul[i][1], tabul[i][2], tabul[i][3], tabul[i][4]);
	}
		
	printf ("\n --------------------- --------------------- --------------------- --------------------- --------------------- \n");
	printf (" |   |   |   |   |   | |   |   |   |   |   | |   |   |   |   |   | |   |   | %c | %c | %c | |   |   |   |   |   | ", tabul[24][5], tabul[25][5], tabul[26][5]);	
	printf ("\n --------------------- --------------------- --------------------- --------------------- --------------------- \n");
	printf (" |   | C |   |   |   | |   |   |   |   |   | |   | %c | %c | %c |   | |   |   | %c |   | %c | |   |   |   | F |   | ", tabul[11][5], tabul[12][5], tabul[13][5], tabul[23][5], tabul[27][5]);	
	printf ("\n ----- O ------------- --------------------- --------------------- --------------------- -------------   ----- \n");
	printf (" |   | M | %c | %c | %c | | %c | %c | %c | %c | %c | | %c | %c |   | %c | %c | | %c |   | %c |   | %c | | %c | %c | %c | I |   | ", tabul[1][5], tabul[2][5], tabul[3][5], tabul[4][5], tabul[5][5], tabul[6][5], tabul[7][5], tabul[8][5], tabul[9][5], tabul[10][5], tabul[14][5], tabul[15][5], tabul[16][5], tabul[22][5], tabul[28][5], tabul[29][5], tabul[30][5], tabul[31][5]);	
	printf ("\n ----- E ------------- --------------------- --------------------- --------------------- -------------   ----- \n");
	printf (" |   | . |   |   |   | |   |   |   |   |   | |   |   |   |   |   | | %c |   | %c |   |   | |   |   |   | M |   | ", tabul[17][5], tabul[21][5]);	
	printf ("\n --------------------- --------------------- --------------------- --------------------- --------------------- \n");
	printf (" |   |   |   |   |   | |   |   |   |   |   | |   |   |   |   |   | | %c | %c | %c |   |   | |   |   |   |   |   | ", tabul[18][5], tabul[19][5], tabul[20][5]);
	printf ("\n --------------------- --------------------- --------------------- --------------------- --------------------- \n");
	
	return 0;
}

// funcao para gerar o valor que sera impresso caso mais de um jogador esteja na mesma posicao | function to generate the value that will be printed if more than one player is in the same position
int peca (int a, int b, int c, int d, int e) {
	int f = 0;
	
	if (b == 0)
		f ++;
	if (c == 0)
		f ++;
	if (d == 0)
		f ++;
	if (e == 0)
		f ++;
	
	switch (f) {
		case 0:
			return 52;
			break;
		case 1:
			return 51;
			break;
		case 2:
			return 50;
			break;
		case 3:
			if (b != 0)
				return b;
			if (c != 0)
				return c;
			if (d != 0)
				return d;
			if (e != 0)
				return e;
			break;
		case 4:
			return a;
			break;
	}	
}

// funcao para imprimir o cabecalho da tela | function to print the screen header
int cabecalho (int x, int y) {
	printf ("\n _____________________________________________________________________________________________________________ \n");
	if (y != 0)
	printf ("\n                                                 %da RODADA: ", y);
	printf ("\n                                                 %do JOGADOR: ", x+1);
	printf ("\n _____________________________________________________________________________________________________________ \n");
	return 0;
}

// funcao para imprimir a tela de escolha de quantidade de jogadores | function to print the player quantity selection screen
int jogadores (int x) {
	int resp=0;
	while (resp == 0) {
		printf ("\n\n Quantidade de Jogadores: \n [1] Um Jogador\n [2] Dois Jogadores\n [3] Tres Jogadores\n [4] Quatro Jogadores\n Resposta: ");
		scanf ("%d", &resp);
		switch (resp){
			case 1:
				printf ("\n Opcao Escolhida: \"Um Jogador\"\n\n ----------\n ");
				system ("pause");
				system ("cls");				
				break;
			case 2:
				printf ("\n Opcao Escolhida: \"Dois Jogadores\"\n\n ----------\n ");
				system ("pause");
				system ("cls");	
				break;
			case 3:
				printf ("\n Opcao Escolhida: \"Tres Jogadores\"\n\n ----------\n ");
				system ("pause");
				system ("cls");	
				break;
			case 4:
				printf ("\n Opcao Escolhida: \"Quatro Jogadores\"\n\n ----------\n ");
				system ("pause");
				system ("cls");	
				break;
			default:
				resp = 0;
				system ("cls");	
				break;
		}
	}
	
	return resp;
}

// funcao para imprimir os dados dos personagens jogaveis | function to print the data of playable characters
int personagens (int x) {
	int resp, y=0;
	for (i=0;i<qtd;i++) {
		resp = 0;
			
		while (resp == 0) {
			cabecalho (i, 0);
			
			printf ("\n          DRUIDA:          |           BARDO:          |         GUERREIRO:        |           LADINO:         ");
			printf ("\n                           |                           |                           |                           ");
			printf ("\n    HISTORIA:              |    HISTORIA:              |    HISTORIA:              |    HISTORIA:              ");
			printf ("\n Desde jovem, foi          | Criado em uma familia de  | Uma vez fora renomado por | Nascido nas ruas sombrias ");
			printf ("\n escolhido pelos espiritos | artistas, descobriu desde | sua bravura e lealdade,   | de uma cidade agitada,    ");
			printf ("\n da floresta para ser seu  | cedo o poder              | mas foi traido por        | aprendeu desde cedo a     ");
			printf ("\n guardiao e emissario. Ele | transformador da musica.  | aqueles em quem confiava  | arte da sobrevivencia e   ");
			printf ("\n passou decadas            | Inspirado por suas        | e acusado injustamente de | da trapaca. Ele se        ");
			printf ("\n aprimorando suas          | experiencias de vida, se  | um crime que nao cometeu. | destacou como um habil    ");
			printf ("\n habilidades druidicas,    | dedicou a compartilhar    | Desonrado e banido de sua | ladrao, utilizando suas   ");
			printf ("\n aprendendo os segredos    | historias de esperanca e  | terra natal, agora busca  | habilidades para se       ");
			printf ("\n das plantas, dos animais  | superacao por meio de     | provar sua inocencia e    | infiltrar e adquirir      ");
			printf ("\n e dos elementos.          | suas melodias cativantes. | restaurar sua honra.      | tesouros preciosos.       ");
			printf ("\n                           |                           |                           |                           ");
			printf ("\n    VANTAGENS:             |    VANTAGENS:             |    VANTAGENS:             |    VANTAGENS:             ");
			printf ("\n Animais e Sobrevivencia   | Comerciantes e Andarilhos | Combates e Suportes       | Ladroes e Furtividade     ");
			printf ("\n                           |                           |                           |                           ");
			printf ("\n    DESVANTAGENS:          |    DESVANTAGENS:          |    DESVANTAGENS:          |    DESVANTAGENS:          ");
			printf ("\n Comerciantes e Andarilhos | Animais e Sobrevivencia   | Ladroes e Furtividade     | Combates e Suportes       ");
			
			printf ("\n\n Escolher Personagem:\n [1] Druida\n [2] Bardo\n [3] Guerreiro\n [4] Ladino\n Resposta: ");
			scanf ("%d", &resp);
			switch (resp){
				case 1:
					printf ("\n Personagem Escolhido: \"Druida\"\n\n ----------\n ");
					system ("pause");
					system ("cls");				
					break;
				case 2:
					printf ("\n Personagem Escolhido: \"Bardo\"\n\n ----------\n ");
					system ("pause");
					system ("cls");	
					break;
				case 3:
					printf ("\n Personagem Escolhido: \"Guerreiro\"\n\n ----------\n ");
					system ("pause");
					system ("cls");	
					break;
				case 4:
					printf ("\n Personagem Escolhido: \"Ladino\"\n\n ----------\n ");
					system ("pause");
					system ("cls");	
					break;
				default:
					resp = 0;
					system ("cls");	
					break;
			}
			jogador[i].personagem = resp;
		}
	}
	return 0;
}

// funcao para mudar a cor da tela | function to change the screen color
int cor (int x) {
	
	switch (x) {
		case 1:
			system ("color 02");
			break;
		case 2:
			system ("color 06");
			break;
		case 3:
			system ("color 04");
			break;	
		case 4:
			system ("color 09");
			break;	
	}		
	return 0;
}

// funcao para receber uma pergunta | function to receive a question
int perguntas (int x, int y) {
	int resp=0;
	
	i = 0;
	
	i = aleatorio (0);
	
	if (y < 4)
		i = i + 0;
	else if (y < 9)
		i = i + 8;
	else if (y < 16)
		i = i + 16;
	else if (y < 29)
		i = i + 24;
	else if (y < 32)
		i = i + 32;
	else
		i = i + 40; 
	
	while (resp == 0) {
		printf ("\n Evento Obtido: %s.\n\n %s\n\n Pergunta: %s\n\n Resposta: ",carta[i].tipo, carta[i].dica, carta[i].pergunta);
		scanf ("%d", &resp);
		if ((resp != 1) && (resp != 2) && (resp != 3) && (resp!= 4)) {
			resp = 0;
			system ("cls");	
			}
	}
	
	if (resp == carta[i].resposta){
		printf ("\n Resposta Correta!");
		if (x == carta[i].desvantagem) {
			printf ("\n\n %s", carta[i].certo1);
			printf ("\n\n ----------\n ");
			system ("pause");
			system ("cls");
			return 0;
		}
		else {
			printf ("\n\n %s", carta[i].certo2);
			printf ("\n\n ----------\n ");
			system ("pause");
			system ("cls");
			if (i > 40)
				return 4;
			return 1;
		}		
	}
	else {
		printf ("\n Resposta Errada! A resposta correta era: %s", carta[i].certa);
		if (x == carta[i].vantagem) {
			printf ("\n\n %s", carta[i].errado1);
			printf ("\n\n ----------\n ");
			system ("pause");
			system ("cls");
			return 0;
		}
		else {
			printf ("\n\n %s", carta[i].errado2);
			printf ("\n\n ----------\n ");
			system ("pause");
			system ("cls");
			if (i > 40)
				return -4;
			return -1;
		}
	}
}

// funcao para gerar um numero aleatorio | function to generate a random number
int aleatorio (int x) {
	srand (time(NULL));
	int y;
	y = 1 + rand()%(8);	
	return y;
}

// funcao para imprimir a capa do jogo | function to print the game cover
int capa (int x) {
	printf ("\n                                                   |>>>                                       ");  
	printf ("\n                                                   |                                          ");
	printf ("\n                                     |>>>      _  _|_  _         |>>>                         ");           
	printf ("\n                                     |        |;| |;| |;|        |                            ");
	printf ("\n                                 _  _|_  _    \\\\.    .  /    _  _|_  _                      ");
	printf ("\n                                |;|_|;|_|;|    \\\\:. ,  /    |;|_|;|_|;|                     ");
	printf ("\n                                \\\\..      /    ||;   . |    \\\\.    .  /                   ");
	printf ("\n                                 \\\\.  ,  /     ||:  .  |     \\\\:  .  /                    ");
	printf ("\n                                  ||:   |_   _ ||_ . _ | _   _||:   |                         ");
	printf ("\n                                  ||:  .|||_|;|_|;|_|;|_|;|_|;||:.  |                         ");
	printf ("\n                                  ||:   ||.    .     .      . ||:  .|                         ");
	printf ("\n                                  ||: . || .     . .   .  ,   ||:   |       \\,/              ");
	printf ("\n                                  ||:   ||:  ,  _______   .   ||: , |            /`\\         ");
	printf ("\n                                  ||:   || .   /+++++++\    . ||:   |                         ");
	printf ("\n                                  ||:   ||.    |+++++++| .    ||: . |                         ");
	printf ("\n                               __ ||: . ||: ,  |+++++++|.  . _||_   |                         ");
	printf ("\n                      ____--`~    '--~~__|.    |+++++__|----~    ~`---,                       ");
	printf ("\n                 -~--~                   ~---__|,--~'                  ~~----_____-~'	     ");
	printf ("\n");
	printf ("\n   _____                 _                     _         _____      _            _            _                    ");
	printf ("\n  / ____|               (_)                   | |       / ____|    | |          | |          (_)                   ");
	printf ("\n | |     _ __ ___  _ __  _  ___ __ _ ___    __| | ___  | |     __ _| | ___ _   _| | __ _ _ __ _  __ _              ");
	printf ("\n | |    | '__/ _ \\| '_ \\| |/ __/ _` / __|  / _` |/ _ \\ | |    / _` | |/ __| | | | |/ _` | '__| |/ _` |          ");
	printf ("\n | |____| | | (_) | | | | | (__ (_| \\__ \\ | (_| |  __/ | |____ (_| | | (__| |_| | | (_| | |  | | (_| |           ");
	printf ("\n  \\_____|_|  \\___/|_| |_|_|\\___\\__,_|___/  \\__,_|\\___|  \\_____\\__,_|_|\\___|\\__,_|_|\\__,_|_|  |_|\\__,_| ");
	printf ("\n\n\n ");
	system ("pause");
	system ("cls");                                                                                                     
	return 0;                                                                                                      
}

// funcao para imprimir a historia do jogo | function to print the game history
int historia (int x) {
	
	printf ("\n _____________________________________________________________________________________________________________ \n");
	printf ("\n                                                 HISTORIA: ");
	printf ("\n _____________________________________________________________________________________________________________ \n");

	printf (" \n Em Calcularia, reino onde os fluxos dos rios sao tao limpidos quanto equacoes bem resolvidas e os  campos se");
	printf (" \n estendem ate ao infinito horizonte, o eco de batalha ainda ressoa. As imponentes muralhas do reino ");
	printf (" \n testemunharam um ataque violento, onde forcas malignas irromperam como uma funcao exponencial, crescendo ");
	printf (" \n rapidamente e inundando a terra como uma integral indefinida. ");
	printf (" \n  ");
	printf (" \n O ataque, tao repentino quanto implacavel, deixou o reino cambaleando sob o peso da destruicao. Vilas outrora ");
	printf (" \n pacificas agora estao em ruinas, suas casas incendiadas e suas ruas manchadas pelo sangue dos inocentes. O ");
	printf (" \n povo, atordoado pela carnificina, busca abrigo e esperanca onde quer que possa ser encontrada. ");
	printf (" \n  ");
	printf (" \n No centro desse caos uma tragedia ainda mais angustiante se desenrola: a princesa, joia do reino, foi ");
	printf (" \n capturada pelos invasores. O rei, tomado pela aflicao, convoca os mais valentes e habilidosos aventureiros do ");
	printf (" \n reino para uma missao crucial: resgatar sua filha e herdeira. ");
	printf (" \n  ");
	printf (" \n Os aventureiros, movidos pela promessa de recompensa, honra ou dever, respondem ao chamado do rei. Entre eles ");
	printf (" \n um druida sabio, cujo vinculo com a natureza e tao antigo quanto os segredos das arvores, um habil ladino em ");
	printf (" \n busca de aventura e tesouros, um destemido guerreiro em busca de recuperar sua honra e um bardo encantador ");
	printf (" \n cujas melodias contam historias de esperanca e coragem. ");
	printf (" \n  ");
	printf (" \n Eles irao embarcar em uma jornada epica atraves de terras desconhecidas e perigos insondaveis, enfrentando ");
	printf (" \n criaturas misticas, conspiracoes traicoeiras e desafios que testarao nao apenas suas habilidades, mas tambem ");
	printf (" \n seu raciocinio e logica. Enquanto o sol se aproxima do limite sobre Calcularia, o destino da princesa e do ");
	printf (" \n reino depende das solucoes destes bravos herois, determinados a restaurar a paz perdida.");
	
	printf ("\n\n\n ");
	system ("pause");
	system ("cls");   
	return 0;
}

// funcao que armazena os dados das perguntas | function that stores the question data
int cartas (int x) {
	
	x = 1;// Carta 1
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "COMERCIANTE");
	strcpy (carta[x].dica, "Enquanto deixava o reino, voce avistou uma pequena loja, com curiosidade se aproximou e presenciou o \n comerciante cantarolando alegremente uma cancao: Na funcao de 1o grau AX+B, B representa o valor em que a \n reta da funcao passa pelo eixo Y do grafico, ou seja, quando X for 0.");
	strcpy (carta[x].pergunta, "Na funcao 11X+4, qual e o valor em que a reta passa pelo eixo Y?\n [1] No valor 4.\n [2] No valor 11.\n [3] No valor 7.\n [4] No valor 15." );
	strcpy (carta[x].certa, "[1] No valor 4.");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "Voce sente um desconforto com a presenca do comerciante e decide seguir seu caminho. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce se encanta com os itens do comerciante e compra sapatos novos por 3 moedas de bronze. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce esta sem dinheiro no momento, mas canta uma cancao para o comerciante que lhe entrega um item de graca.\n Continue onde esta.");
	strcpy (carta[x].errado2, "Voce esta sem dinheiro no momento e por isso decide nem olhar os itens da loja. Volte 1 casa.");
	
	x = 2;// Carta 2
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "COMBATE");
	strcpy (carta[x].dica, "Passando pelo distrito comercial, voce se surpreende ao ouvir alguem gritando: Na funcao de 1o grau AX+B, B \n representa o valor em que a reta da funcao passa pelo eixo Y do grafico, ou seja, quando X for 0. Olhando na \n direcao da voz, voce ve um goblin remanescente do exercito inimigo atacando um aldeao inocente.");
	strcpy (carta[x].pergunta, "Na funcao 7X-2, qual e o valor em que a reta passa pelo eixo Y?\n [1] No valor 7.\n [2] No valor -2.\n [3] No valor 5.\n [4] No valor 9." );
	strcpy (carta[x].certa, "[2] No valor -2.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Voce ignora o aldeao e pensa consigo mesmo: \"Pelo menos ele nao esta me atacando\". Depois, volta a se \n concentrar no seu caminho. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce se dispoe a ajuda-lo e o goblin nao era um grande desafio, conseguindo vence-lo facilmente. Avance 1 \n casa.");
	strcpy (carta[x].errado1, "Voce nao suporta ver um inocente sofrer e vai ajuda-lo, mas o goblin era mais forte do que imaginava e com \n dificuldades consegue vence-lo. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce fica imovel vendo o ataque do inimigo sem conseguir reagir, por sorte um soldado aparece e ajuda o \naldeao, eliminando o goblin com facilidade. Volte 1 casa.");
	
	x = 3;// Carta 3
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "ANIMAIS");
	strcpy (carta[x].dica, "Voce esta parado em frente a uma multidao de aldeoes que estao interditando o caminho e discutindo \n fervorosamente. Na funcao de 2o grau AX^(2) + BX + C, C representa o valor em que a parabola da funcao passa \n pelo eixo Y do grafico, ou seja, quando X for 0, voce escuta um deles dizer. Procurando um meio de passar \n pelas pessoas, voce observa seus arredores e nota uma pequena matilha de caes entrando em um corredor.");
	strcpy (carta[x].pergunta, "Na funcao 2X^(2) + 3X + 5, qual e o valor em que a reta passa pelo eixo Y?\n [1] No valor 2.\n [2] No valor 3.\n [3] No valor 5.\n [4] No valor 8." );
	strcpy (carta[x].certa, "[3] No valor 5.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "Voce ignora os animais e comeca a tocar uma cancao, sua musica distrai os aldeoes te dando uma oportunidade \n para passar por eles. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce entra no corredor e percebe um labirinto entre as casas. Seguindo os caes, nao demora muito a se ver a \n frente dos aldeoes. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce entra no corredor e percebe um labirinto entre as casas. Em pouco tempo voce se perde e quando menos \n esperava, os caes reaparecem para te ajudar a chegar na saida. Continue onde esta.");
	strcpy (carta[x].errado2, "Muito intrigado com a discussao dos aldeoes, voce ignora os animais e entra na conversa dizendo: \n f(x) = AX + B. Volte 1 casa.");
	
	x = 4;// Carta 4
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "LADRAO");
	strcpy (carta[x].dica, "Quase proximo a saida do reino, voce sente alguem te observando, olhando aos arredores nao encontra nada fora \n do comum. Mas quando se vira pra seguir a diante, uma lamina e colocada em seu pescoco e uma voz desconhecida \n diz: Na funcao de 1o grau AX+B, A representa a inclinacao da reta, valores de A positivos teremos uma reta \n crescente e valores de A negativos teremos uma reta decrescente.");
	strcpy (carta[x].pergunta, "Na funcao AX-3, qual e o valor de A, para que a reta seja crescente?\n [1] No valor -3.\n [2] No valor -1.\n [3] No valor 0.\n [4] No valor 3." );
	strcpy (carta[x].certa, "[4] No valor 3.");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "Voce saca sua espada fazendo o ladrao te soltar e fugir com medo do conflito. Mas quando vai conferir, \n algumas de suas moedas desapareceram. Continue onde esta.");
	strcpy (carta[x].certo2, "Enquanto pensa no que fazer um soldado aparece gritando: f(x) = AX+B. Fazendo com que o ladrao suma \n misteriosamente. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce se identifica como ladino tambem e o estranho imediatamente se afasta enquanto se desculpa, indo embora \n da mesma forma que surgiu. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce pega algumas moedas de bronze e as deixa cair no chao que somem misteriosamente junto com o ladrao. \n Volte 1 casa.");
	
	x = 5;// Carta 5
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "ANDARILHO");
	strcpy (carta[x].dica, "Um andarilho de aparencia simples e vestes claras o aborda enquanto voce caminhava, se apresenta \n humildemente, lhe estendendo a sua mao e dizendo: Em uma funcao o seu grau e definido pelo expoente mais \n alto, se o X nao possuir expoente essa funcao e de 1o grau. \n\n Obs.: X^(Y), Y e o expoente.");
	strcpy (carta[x].pergunta, "Na funcao 2X^(2) + 5X - 3X^(4) + X^(3), qual e o grau da funcao?\n [1] A funcao e de 1o grau.\n [2] A funcao e de 2o grau.\n [3] A funcao e de 3o grau.\n [4] A funcao e de 4o grau." );
	strcpy (carta[x].certa, "[4] A funcao e de 4o grau.");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "O andarilho esta falando diretamente com voce, extremamente constrangido, voce se transforma em um gato e se \n afasta rapidamente. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce entrega a ele duas moedas de bronze e surpreso pela bondade, ele oferece a voce uma pocao de velocidade, \n ao bebe-la voce se sente mais leve. Avance 1 casa.");
	strcpy (carta[x].errado1, "O andarilho esta te pedindo dinheiro, voce nao tem o suficiente para dividir e explica isso, porem decidi \n cantar uma cancao para animar o dia dele. Continue onde esta.");
	strcpy (carta[x].errado2, "O andarilho esta te pedindo dinheiro, voce nao tem o suficiente para dividir, esperando uma oportunidade de \n distracao dele, voce foge envergonhado. Volte 1 casa.");
	
	x = 6;// Carta 6
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "SUPORTE");
	strcpy (carta[x].dica, "Voce se ve em frente a uma grande carroca de repolhos parada na estrada, olhando com mais atencao percebe a \n presenca de um humilde senhor tentando a levantar sozinho para que possa encaixar uma roda que esta caida ao \n seu lado. O aldeao nota voce, olha em sua direcao e diz: Em uma funcao o seu grau e definido pelo expoente \n mais alto, se o X nao possuir expoente essa funcao e de 1o grau. \n\n Obs.: X^(Y), Y e o expoente.");
	strcpy (carta[x].pergunta, "?\n [1] A funcao e de 3o grau.\n [2] A funcao e de 4o grau.\n [3] A funcao e de 5o grau.\n [4] A funcao e de 1o grau." );
	strcpy (carta[x].certa, "[3] A funcao e de 5o grau.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "Voce encara o senhor, deixa ele falando sozinho e segue em rumo a seu caminho. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce se solidariza com o senhor, e o ajuda a levantar a carroca enquanto ele encaixa novamente a roda no \n lugar. Para lhe agradecer o aldeao lhe oferece uma carona. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce ajuda o senhor a levantar a carroca enquanto ele encaixa novamente a roda no lugar, mas recusa a ser \n recompensado em troca. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce tenta ajudar o senhor, mas a carroca e muito mais pesada do que aparenta, sera preciso chamar mais \n aldeoes para ajudar voces. Volte 1 casa.");
	
	x = 7;// Carta 7
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "SOBREVIVENCIA");
	strcpy (carta[x].dica, "Enquanto andava distraido pela estrada do reino, voce escuta um desconhecido gritar: Na funcao de 1o grau \n AX+B, A representa a inclinacao da reta, valores de A positivos teremos uma reta crescente e valores de A \n negativos teremos uma reta decrescente. Olhando na direcao da voz, voce percebe uma carroca desgovernada indo \n em sua direcao.");
	strcpy (carta[x].pergunta, "Na funcao AX+4, qual e valor de A, para que a reta seja decrescente?\n [1] No valor 5.\n [2] No valor -5.\n [3] No valor 3.\n [4] No valor 0." );
	strcpy (carta[x].certa, "[2] No valor -5.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "A carroca esta muito proxima, voce nao vai conseguir desviar, mas a sorte esta ao seu lado e a carroca muda \n de direcao misteriosamente. Continue onde esta.");
	strcpy (carta[x].certo2, "Habilmente voce desvia da carroca e para se desculpar por quase lhe atropelar, o carroceiro lhe oferece uma \n carona. Avance 1 casa.");
	strcpy (carta[x].errado1, "A carroca esta muito proxima, voce nao vai conseguir desviar, mas quando o cavalo olha para voce \n instintivamente ele consegue frear a carroca. Continue onde esta.");
	strcpy (carta[x].errado2, "Sem tempo para desviar a carroca tromba com voce, mas para se desculpar o carroceiro o leva ate o curandeiro \n mais proximo. Volte 1 casa.");
	
	x = 8;// Carta 8
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "FURTIVIDADE");
	strcpy (carta[x].dica, "Passando por uma regiao em ruinas do reino, voce ouve grunhidos distantes. Com cautela, voce se aproxima e \n avista um bando de goblins conversando: Na funcao de 2o grau AX^(2) + BX + C, C representa o valor em que a \n parabola da funcao passa pelo eixo Y do grafico, ou seja, quando X for 0.");
	strcpy (carta[x].pergunta, "Na funcao 3X^(2) - 4X - 3, qual e o valor em que a reta passa pelo eixo Y?\n [1] No valor -3.\n [2] No valor 3.\n [3] No valor -4.\n [4] No valor 2." );
	strcpy (carta[x].certa, "[1] No valor -3.");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "Notando a sua presenca, os goblins se viram para voce, deixando-o sem alternativa a nao ser enfrenta-los em \n combate. Continue onde esta.");
	strcpy (carta[x].certo2, "Notando o perigo, voce se move furtivamente para longe do grupo, escapando com sucesso sem ser detectado. \n Avance 1 casa.");
	strcpy (carta[x].errado1, "Notam a sua presenca, mas apesar disso, voce consegue se esconder e se afastar furtivamente sem ser avistado \n novamente. Continue onde esta.");
	strcpy (carta[x].errado2, "Notando o perigo, voce tenta se esgueirar, mas e avistado. Decidido a evitar o confronto, voce escolhe fugir \n em vez de entrar em combate. Volte 1 casa.");
	
	x = 9;// Carta 9
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "COMERCIANTE");
	strcpy (carta[x].dica, "Enquanto cruzava a ponte, voce viu algo inusitado: um pequeno rato, vestido com um colete colorido e um \n chapeu elegante, exibindo uma pequena mesa cheia de bugigangas. Em frente a ela havia uma placa com uma \n minuscula frase escrita: O expoente de uma variavel, representa quantas vezes voce vai repetir esse número na \n multiplicacao, X^(2) repete duas vezes, X^(3) repete tres e assim sucessivamente.");
	strcpy (carta[x].pergunta, "?\n [1] O f(x) = 15.\n [2] O f(x) = 10.\n [3] O f(x) = 25.\n [4] O f(x) = 20." );
	strcpy (carta[x].certa, "[3] O f(x) = 25.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "Encantado, voce se aproximou e horas se passaram enquanto jogava conversa fora com o rato comerciante. \n Continue onde esta.");
	strcpy (carta[x].certo2, "Intrigado, voce se aproximou e foi recebido com um sorriso amigavel do rato comerciante, que comecou a lhe \n mostrar seus produtos. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce se aproximou enquanto tocava uma cancao e para sua surpresa, o comerciante tambem era um otimo músico, \n ele entrou na melodia com sua pequena lira. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce decidiu se aproximar, o que inesperadamente acabou assuntando o pequeno comerciante, que rapidamente \n guardou suas mercadorias e fugiu velozmente. Volte 1 casa.");
	
	x = 10;// Carta 10
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "COMBATE");
	strcpy (carta[x].dica, "Caminhando pela ponte, voce de repente se depara com um grupo de serpentes venenosas, que se contorciam e \n sibilavam ameacadoramente: Na funcao de 2o grau AX^(2) + BX + C, A representa a direcao da concavidade da \n parabola da funcao, A maior que 0 indica que a concavidade e para cima e A menor que 0 indica que a \n concavidade e para baixo. Instintivamente voce recua percebendo o perigo iminente.");
	strcpy (carta[x].pergunta, "Na funcao AX^(2) + 5X - 3, qual e valor de A, para que a concavidade seja para baixo?\n [1] No valor 0.\n [2] No valor -5.\n [3] No valor 5.\n [4] No valor 3." );
	strcpy (carta[x].certa, "[2] No valor -5.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Elas te atacam, mas facilmente voce consegue desviar. Todavia elas nao desistem, continuam o confronto \n enquanto voce se esquiva com sucesso. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce pega uma arma e a balanca vigorosamente na frente das feras as fazendo voltarem amedrontadas para o \n lugar de onde vieram. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce pega sua arma e a balanca contra elas, perfurando facilmente uma serpente, fazendo com que as outras \n fujam amedrontadas. Continue onde esta.");
	strcpy (carta[x].errado2, "No entanto, antes que possa agir, uma voz misteriosa ecoa pelo vento, fazendo as serpentes irem para a \n escuridao das sombras. Volte 1 casa.");
	
	x = 11;// Carta 11
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "ANIMAIS");
	strcpy (carta[x].dica, "Enquanto avancava pela ponte, uma nuvem de gaivotas surgiu repentinamente a sua frente, voando em circulos ao \n seu redor e emitindo cacarejos estridentes: Na funcao de 2o grau AX^(2) + BX + C, o DELTA indica quantas \n raizes essa funcao possui, DELTA maior que 0 indica que tem 2 raizes, DELTA menor que 0 indica que nao tem \n raizes e DELTA igual a 0 indica que tem 1 raiz.");
	strcpy (carta[x].pergunta, "Na funcao X^(2) + 2X - 3, onde DELTA equivale a 16, quantas raizes possui?\n [1] Possui 3 raizes.\n [2] Possui 2 raizes.\n [3] Possui 1 raiz.\n [4] Possui 0 raizes." );
	strcpy (carta[x].certa, "[2] Possui 2 raizes.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Determinado a prosseguir, voce tentou usar sua melodia para acalma-las, mas isso so piorou a situacao, \n tornando as gaivotas mais agressivas. Continue onde esta.");
	strcpy (carta[x].certo2, "Determinado a prosseguir, voce continuou a travessia apesar da presenca obstinada das gaivotas. Avance 1 \n casa.");
	strcpy (carta[x].errado1, "Determinado a entender a situacao, voce tentou conversar com elas, que aos poucos foram se acalmando e \n pousando na ponte uma a uma. Continue onde esta.");
	strcpy (carta[x].errado2, "Determinado a prosseguir, voce tentou afasta-las agitando seus bracos, mas elas se mostraram mais motivadas a \n bloquear o seu caminho. Volte 1 casa.");
	
	x = 12;// Carta 12
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "LADRAO");
	strcpy (carta[x].dica, "Atravessando a ponte, voce foi surpreendido por um individuo sorrateiro, emergindo das sombras com passos \n furtivos. Rapido como um raio, o ladrao tentou desviar a sua atencao fazendo movimentos ageis para tentar \n roubar seus pertences e falando: Na funcao de 1o grau AX+B, a raiz representa o valor em que a reta da funcao \n passa pelo eixo X do grafico, ou seja, quando Y for 0 (o resultado e igual a 0).");
	strcpy (carta[x].pergunta, "Na funcao 2X-10, qual e a sua raiz?\n [1] A raiz e 20.\n [2] A raiz e 12.\n [3] A raiz e -8.\n [4] A raiz e 5." );
	strcpy (carta[x].certa, "[4] A raiz e 5.");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "Voce acaba caindo no truque do ladrao e quando percebe ja era tarde, o mesmo havia desaparecido e seus \n pertences tambem. Continue onde esta.");
	strcpy (carta[x].certo2, "Contudo, voce estava alerta e nao se deixou enganar facilmente. Conseguindo frustrar as tentativas do ladrao \n e manter seus bens em seguranca. Avance 1 casa.");
	strcpy (carta[x].errado1, "Contudo, voce nao se distrai facilmente e o ladrao, percebendo que nao teria sucesso, desaparece tao \n rapidamente quanto apareceu. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce acaba caindo no truque do ladrao e quando percebe ja era tarde, o mesmo havia desaparecido e seus \n pertences tambem. Volte 1 casa.");
	
	x = 13;// Carta 13
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "ANDARILHO");
	strcpy (carta[x].dica, "Avancando pela ponte voce avista um andarilho solitario a distancia. Ele estava cabisbaixo perdido em seus \n pensamentos. Ao se aproximar, o andarilho ergueu o olhar para voce e sorriu com gentileza. Com uma voz calma \n e tranquila comecou a te contar: Na funcao de 2o grau AX^(2) + BX + C, substitua X pelo seu valor, \n multiplique o seu quadrado por A, multiplique o seu valor por B, e some todos os resultados com C.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao X^(2) + 2X + 6, quando X for 3?\n [1] O f(x) = 21.\n [2] O f(x) = 18.\n [3] O f(x) = 15.\n [4] O f(x) = 10." );
	strcpy (carta[x].certa, "[1] O f(x) = 21.");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "Com descrenca, voce se transforma em uma coruja e levanta voo se distanciando do andarilho confuso. Continue \n onde esta.");
	strcpy (carta[x].certo2, "Depois de um breve momento de conversa, o andarilho seguiu seu caminho, deixando voce inspirado para \n continuar sua jornada. Avance 1 casa.");
	strcpy (carta[x].errado1, "O andarilho compartilhou palavras de sabedoria e encorajamento, oferecendo dicas valiosas sobre o caminho que \n ainda estava por vir. Continue onde esta.");
	strcpy (carta[x].errado2, "Horas se passam enquanto o andarilho lhe conta sobre a sua vida e as reflexoes que sua jornada o trouxe ate o \n momento. Volte 1 casa.");
	
	x = 14;// Carta 14
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "SUPORTE");
	strcpy (carta[x].dica, "Cruzando a ponte, voce avistou uma figura solitaria sentada a beira do abismo, parecendo abatida. Ao se \n aproximar, percebeu que era um senhor idoso, com os olhos cheios de tristeza enquanto jogava palavras aos \n ventos: Na funcao de 1o grau AX/B, voce substitui X pelo seu valor, multiplica ele pelo valor de A e divide \n pelo valor de B para obter o resultado.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao 3X/2, quando X for 4?\n [1] O f(x) = 6.\n [2] O f(x) = 4.\n [3] O f(x) = 2.\n [4] O f(x) = 8." );
	strcpy (carta[x].certa, "[1] O f(x) = 6.");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "Com suspeitas do senhor misterioso, voce o ignora completamente e continua sua jornada. Continue onde esta.");
	strcpy (carta[x].certo2, "Com compaixao, voce se aproximou e iniciou uma conversa, com o passar do tempo, o senhor lhe agradeceu e \n partiu em sua propria jornada. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce iniciou uma conversa lhe oferecendo ajuda, fazendo o senhor te presentear com um sorriso de gratidao, \n enquanto desaparecia misteriosamente. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce iniciou uma conversa, descobrindo que ele estava passando por dificuldades, e se solidarizando, voce \n fica as proximas hora ao lado senhor o confortando. Volte 1 casa.");
	
	x = 15;// Carta 15
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "SOBREVIVENCIA");
	strcpy (carta[x].dica, "Voce atravessava a ponte, quando uma tempestade surge subitamente, transformando o ceu claro e calmo em um \n ceu escuro com ventos e chuvas fortes. Enquanto isso voce reflete interiormente: Na funcao de 1o grau AX+B, \n voce substitui X pelo seu valor, multiplica ele pelo valor de A e soma com o valor de B para obter o \n resultado.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao 3X+2, quando X for 2?\n [1] O f(x) = 5.\n [2] O f(x) = 8.\n [3] O f(x) = 6.\n [4] O f(x) = 7." );
	strcpy (carta[x].certa, "[2] O f(x) = 8.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Voce ajeita seu instrumento entre suas roupas, procurando protege-lo da melhor forma possivel, na esperanca \n de que a tempestade passe em breve. Continue onde esta.");
	strcpy (carta[x].certo2, "A chuva dificulta sua visao, mas voce nao se deixar vencer por uma tempestade. Com coragem, continua se \n movendo e lutando contra o temporal. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce se agarra ao que pode e decide esperar a tempestade passar e inesperadamente, assim como surgiu, a \n tempestade vai embora. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce se agarra ao que pode e decide esperar a tempestade passar, mas horas se passam ate que a tempestade \n comece a se acalmar. Volte 1 casa.");
	
	x = 16;// Carta 16
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "FURTIVIDADE");
	strcpy (carta[x].dica, "Avancando pela ponte, voce avistou um bando de harpias pairando no ceu, pareciam estar procurando por presas \n enquanto se comunicavam entre si: Na funcao de 1o grau AX+B, voce substitui X pelo seu valor, multiplica ele \n pelo valor de A e soma com o valor de B para obter o resultado.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao 2X+4, quando X for 3?\n [1] O f(x) = 8.\n [2] O f(x) = 7.\n [3] O f(x) = 10.\n [4] O f(x) = 9." );
	strcpy (carta[x].certa, "[3] O f(x) = 10.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, ". Avance 1 casa.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, ". Volte 1 casa.");
	
	x = 17;// Carta 17
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "COMERCIANTE");
	strcpy (carta[x].dica, "Entre as sombras da floresta, sob um amontoado de folhas, voce se encontra com um comerciante elfico usando \n trajes exoticos, com um aceno gracioso ele o cumprimenta dizendo: Na funcao de 2o grau AX^(2) + BX + C, o \n DELTA indica quantas raizes essa funcao possui, DELTA maior que 0 indica que tem 2 raizes, DELTA menor que 0 \n indica que nao tem raizes e DELTA igual a 0 indica que tem 1 raiz.");
	strcpy (carta[x].pergunta, "Na funcao X^(2) + 2X - 1, onde DELTA equivale a 0, quantas raizes possui?\n [1] Tem 0 raizes.\n [2] Tem 1 raiz.\n [3] Tem 2 raizes.\n [4] Tem 3 raizes." );
	strcpy (carta[x].certa, "[2] Tem 1 raiz.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Se sentindo ameacado, ao sair da visao do mercador, voce se transforma em um esquilo e vai em direcao a \n escuridao da floresta. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce se aproxima cautelosamente e ele o direciona para uma bancada, que continha uma variedade incrivel de \n itens magicos e raros a venda. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce corresponde ao cumprimento do mercador e devolve a gentiliza em forma de uma cancao. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce se aproxima cautelosamente e ele o direciona para uma bancada, que continha uma variedade incrivel de \n mercadorias de baixa qualidade a venda. Volte 1 casa.");
	
	x = 18;// Carta 18
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "COMBATE");
	strcpy (carta[x].dica, "Avancando pela densa floresta, voce escuta vozes conversando: Na funcao de 1o grau AX+B, a raiz representa o \n valor em que a reta da funcao passa pelo eixo X do grafico, ou seja, quando Y for 0 (o resultado e igual a \n 0). Olhando na direcao, voce percebe figuras reptilianas emergindo das sombras, com olhos amarelos e dentes \n afiados.");
	strcpy (carta[x].pergunta, "Na funcao 2X+12, qual e a sua raiz?\n [1] A raiz e -14.\n [2] A raiz e 14.\n [3] A raiz e -6.\n [4] A raiz e 6." );
	strcpy (carta[x].certa, "[3] A raiz e -6.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "Estes sao os Kobolds, mas voce nao os da uma chance para agir, usando as suas habilidades para se esconder \n nas sombras. Continue onde esta.");
	strcpy (carta[x].certo2, "Estes sao os Kobolds, criaturas conhecidas por sua astucia e natureza travessa, eles nao parecem hostis, \n estavam apenas curiosos com sua presenca. Avance 1 casa.");
	strcpy (carta[x].errado1, "Estes sao os Kobolds e aparentam estar hostis em relacao a voce, que saca sua arma e se prepara para o \n combate eminente. Continue onde esta.");
	strcpy (carta[x].errado2, "Estes sao os Kobolds e o lider do grupo, um pouco maior que os outros, emite um rugido fazendo voce fugir com \n medo do combate. Volte 1 casa.");
	
	x = 19;// Carta 19
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "ANIMAIS");
	strcpy (carta[x].dica, "Enquanto andava pela vegetacao da floresta, de repente, uma familia de esquilos ageis aparecem saltando de \n galho em galho ao seu redor, voce tenta espanta-los dizendo: O expoente de uma variavel, representa quantas \n vezes voce vai repetir esse numero na multiplicacao, X^(2) repete duas vezes, X^(3) repete tres e assim \n sucessivamente.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao X^(3), quando X for 3?\n [1] O f(x) = 9.\n [2] O f(x) = 15.\n [3] O f(x) = 21.\n [4] O f(x) = 27." );
	strcpy (carta[x].certa, "[4] O f(x) = 27.");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "Mas e em vao, os esquilos parecem estar em meio a uma brincadeira animada, completamente alheios a sua \n presenca. Continue onde esta.");
	strcpy (carta[x].certo2, "Eles param de se mover e olham para voce com tristeza, como se implorassem por diversao, e voce os acolhe, \n comecando a correr ao lado deles. Avance 1 casa.");
	strcpy (carta[x].errado1, "Ao inves de afasta-los, voce atrai mais alguns animais para a brincadeira, incluindo corujas, passaros e ate \n micos. Continue onde esta.");
	strcpy (carta[x].errado2, "Eles o ignoram e continuam correndo em circulos ao seu redor, desviando-se habilmente dos obstaculos dessa \n flora. Volte 1 casa.");
	
	x = 20;// Carta 20
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "LADRAO");
	strcpy (carta[x].dica, "Caminhando pela floresta, voce presencia uma figura encapuzada emergindo dos arbustos proximos, seus olhos \n brilhavam com astucia enquanto dizia: Na funcao de 1o grau AX-B, voce substitui X pelo seu valor, multiplica \n ele pelo valor de A e subtrai com o valor de B para obter o resultado.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao 2X-3, quando X for 4?\n [1] O f(x) = 11.\n [2] O f(x) = 8.\n [3] O f(x) = 5.\n [4] O f(x) = -1." );
	strcpy (carta[x].certa, "[3] O f(x) = 5.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "O ladrao tenta persuadi-lo a entregar seus pertences, mas voce prontamente puxa sua espada e escudo, \n preparando-se para se defender. Continue onde esta.");
	strcpy (carta[x].certo2, "O ladrao tenta persuadi-lo a entregar seus pertences, mas voce mantem sua guarda elevada e corre, buscando \n dispersa-lo. Avance 1 casa.");
	strcpy (carta[x].errado1, "Ciente da reputacao dos ladroes dessa floresta, voce nao lhe da chance de tentar algo, e com suas proprias \n habilidades, desaparece nas sombras. Continue onde esta.");
	strcpy (carta[x].errado2, "Com uma voz suave, o ladrao tenta persuadi-lo a entregar seus pertences e, caso haja resistencia, adverte que \n nao seria misericordioso. Volte 1 casa.");
	
	x = 21;// Carta 21
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "ANDARILHO");
	strcpy (carta[x].dica, "Enquanto andava perdido na floresta, uma figura solitaria surge a sua frente. O homem parecia conhecer bem o \n ambiente. Voce se aproxima pedindo informacoes: Na funcao de 1o grau AX-B, voce substitui X pelo seu valor, \n multiplica ele pelo valor de A e subtrai com o valor de B para obter o resultado.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao 3X-2, quando X for 2?\n [1] O f(x) = 6.\n [2] O f(x) = 5.\n [3] O f(x) = 4.\n [4] O f(x) = 3." );
	strcpy (carta[x].certa, "[3] O f(x) = 4.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "Para sua infelicidade, o andarilho tambem diz estar perdido, sem saber onde esta ou para onde ir. Continue \n onde esta.");
	strcpy (carta[x].certo2, "O andarilho revela que e morador daquela floresta e indica algumas direcoes para que voce possa seguir seu \n caminho em seguranca. Avance 1 casa.");
	strcpy (carta[x].errado1, "O andarilho se revela um musico em busca de inspiracao para novas cancoes, e voce decide acompanha-lo ate \n encontrar uma saida da floresta. Continue onde esta.");
	strcpy (carta[x].errado2, "Embora o andarilho tenha apontado algumas direcoes, ao segui-las, voce se sente ainda mais perdido do que \n antes. Volte 1 casa.");
	
	x = 22;// Carta 22
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "SUPORTE");
	strcpy (carta[x].dica, "Se aventurando pela densa vegetacao da floresta, voce escuta um chamado de socorro ecoando entre as arvores: \n Na funcao de 2o grau AX^(2) + BX + C, A representa a direcao da concavidade da parabola da funcao, A maior \n que 0 indica que a concavidade e para cima e A menor que 0 indica que a concavidade e para baixo.");
	strcpy (carta[x].pergunta, "Na funcao AX^(2) - 3X + 4, qual e valor de A, para que a concavidade seja para baixo?\n [1] No valor 3.\n [2] No valor 0.\n [3] No valor 4.\n [4] No valor -3." );
	strcpy (carta[x].certa, "[4] No valor -3.");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "Voce ignora o chamado de socorro, preocupado apenas com sua missao e com as riquezas que o aguarda. \n Continue onde esta.");
	strcpy (carta[x].certo2, "Seguindo o som, voce encontra uma jovem elfa aprisionada por uma arvore caida sobre seu corpo, mas consegue \n liberta-la com facilidade. Avance 1 casa.");
	strcpy (carta[x].errado1, "Seguindo o som, voce encontra uma jovem elfa encurralada por um javali selvagem. Voce empunha sua arma e a \n ajuda enfrentando o animal. Continue onde esta.");
	strcpy (carta[x].errado2, "Seguindo o som, voce encontra uma jovem elfa aprisionada por uma arvore caida sobre seu corpo, mas com muita \n dificuldade voce consegue liberta-la. Volte 1 casa.");
	
	x = 23;// Carta 23
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "SOBREVIVENCIA");
	strcpy (carta[x].dica, "Adentrando mais profundamente na floresta, uma tempestade subita desaba sobre a vegetacao, fazendo voce \n rapidamente refletir consigo mesmo: Na funcao de 1o grau AX/B, voce substitui X pelo seu valor, multiplica \n ele pelo valor de A e divide pelo valor de B para obter o resultado.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao 2X/3, quando X for 6?\n [1] O f(x) = 10.\n [2] O f(x) = 8.\n [3] O f(x) = 4.\n [4] O f(x) = 6." );
	strcpy (carta[x].certa, "[3] O f(x) = 4.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "A chuva impiedosa apaga qualquer esperanca de seguranca, enquanto o vento uiva entre as arvores como uma \n cancao de caos. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce corre pela floresta lutando para encontrar um abrigo enquanto os raios cortam o ceu e trovoes ecoam \n entre as arvores. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce corre em um busca desesperada por abrigo, procurando uma clareira ou uma caverna para se proteger da \n furia desta tempestade. Continue onde esta.");
	strcpy (carta[x].errado2, "Com visibilidade reduzida e o terreno encharcado se tornando escorregadio, voce se depara com um novo \n desafio, algo que nunca havia enfrentado antes. Volte 1 casa.");
	
	x = 24;// Carta 24
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "FURTIVIDADE");
	strcpy (carta[x].dica, "Avancando pela floresta, voce se depara com um acampamento improvisado entre as arvores, com mais atencao \n voce ouve vozes: Na funcao de 2o grau AX^(2) + BX + C, substitua X pelo seu valor, multiplique o seu quadrado \n por A, multiplique o seu valor por B, e some todos os resultados com C. Reconhecendo este lugar como um \n acampamento Orc.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao X^(2) + X + 3, quando X for 2?\n [1] O f(x) = 5.\n [2] O f(x) = 7.\n [3] O f(x) = 9.\n [4] O f(x) = 11." );
	strcpy (carta[x].certa, "[3] O f(x) = 9.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "Voce e avistado por um Orc, que prontamente avanca para o ataque, o forcando a ter que se defender contra a \n criatura. Continue onde esta.");
	strcpy (carta[x].certo2, "Percebendo o perigo, voce se move silenciosamente para nao ser notado, enquanto sente o ar impregnado com o \n fedor dos Orcs. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce consegue se mover sorrateiramente pelo acampamento Orc, enquanto furta itens que aparentam possuir algum \n valor. Continue onde esta.");
	strcpy (carta[x].errado2, "Os Orcs avistam voce, e ao perceber a enrascada em que se meteu, voce foge, torcendo para nao ser perseguido \n por muito tempo. Volte 1 casa.");
	
	x = 25;// Carta 25
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "COMERCIANTE");
	strcpy (carta[x].dica, "Se aventurando pelos corredores do labirinto, voce se depara com um comerciante ao virar em uma encruzilhada. Ele sorri \n ao ve-lo e o cumprimenta: Uma das propriedades para derivar uma funcao diz: Em f(x) = X^(n) a funcao derivada sera \n f'(x) = n.X^(n-1), ou seja, voce subtrai 1 do expoente e multiplica o seu valor original por X.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = X^(2) - 2X^(1)?\n [1] O f'(x) = X^(2) - 2x^(1).\n [2] O f'(x) = 2X^(1) - 2x^(0).\n [3] O f'(x) = X^(1) - 2x^(0).\n [4] O f'(x) = 2X^(2) - 2x^(1)." );
	strcpy (carta[x].certa, "[2] O f'(x) = 2X^(1) - 2x^(0).");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Surpreendido pelo inesperado encontro com o comerciante, voce se assusta e, num instante, se transforma em um \n rato, correndo sem olhar para tras. Continue onde esta.");
	strcpy (carta[x].certo2, "Apos buscar entre uma montanha de mercadorias, ele finalmente puxa um mapa do labirinto e oferece para voce \n comprar. Avance 1 casa.");
	strcpy (carta[x].errado1, "Ele estende o mapa do labirinto, nao tendo dinheiro para compra-lo, voce tenta negociar a venda em troca de \n uma cancao. Continue onde esta.");
	strcpy (carta[x].errado2, "Ele estende o mapa do labirinto, mas voce nao tem dinheiro para compra-lo, entao precisa confiar em suas \n proprias habilidades para encontrar a saida. Volte 1 casa.");
	
	x = 26;// Carta 26
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "COMBATE");
	strcpy (carta[x].dica, "Enquanto busca uma saida pelos corredores, seus olhos captam uma escrita na parede alertando sobre uma armadilha: Uma \n das propriedades para derivar uma funcao diz: Em f(x) = X^(n) a funcao derivada sera f'(x) = n.X^(n-1), ou seja, voce \n subtrai 1 do expoente e multiplica o seu valor original por X. Porem, ja era tarde demais, seus pes ja estavam sobre uma \n placa de pressao.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = X^(3) + X^(2)?\n [1] O f'(x) = X^(3) + x^(2).\n [2] O f'(x) = X^(2) + x^(1).\n [3] O f'(x) = 3X^(3) + 2x^(2).\n [4] O f'(x) = 3X^(2) + 2x^(1)." );
	strcpy (carta[x].certa, "[4] O f'(x) = 3X^(2) + 2x^(1).");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "Ao movimentar o pe, um grupo de slimes, criaturas gelatinosas feitas de acido, caem do teto, agilmente, voce \n se oculta, na esperanca de nao ter sido visto. Continue onde esta.");
	strcpy (carta[x].certo2, "Ao movimentar o pe, um conjunto de slimes, criaturas gelatinosas feitas de acido, despencam do teto, \n avancando em sua direcao com a intencao de dissolve-lo vivo. Avance 1 casa.");
	strcpy (carta[x].errado1, "Ao movimentar o pe, um grupo de slimes, criaturas gelatinosas feitas de acido, despencam do teto, preparado, \n voce saca sua arma e parte para o ataque. Continue onde esta.");
	strcpy (carta[x].errado2, "Ao movimentar o pe, um cubo gelatinoso feito de acido, despenca do teto, bloqueando totalmente a passagem por \n esse corredor. Volte 1 casa.");
	
	x = 27;// Carta 27
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "ANIMAIS");
	strcpy (carta[x].dica, "Enquanto caminhava pelos corredores sinuosos do labirinto, um som agudo e inquietante ecoou pelas passagens a sua \n frente: Uma das propriedades para derivar uma funcao diz: Em f(x) = C a funcao derivada sera f'(x) = 0, ou seja, quando \n o valor esta sozinho sem o X ele sera igual a 0.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = 10?\n [1] O f'(x) = 0.\n [2] O f'(x) = 1.\n [3] O f'(x) = 10.\n [4] O f'(x) = 100." );
	strcpy (carta[x].certa, "[1] O f'(x) = 0.");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "De repente, uma nuvem de morcegos vira em um corredor, formando uma parede, impedindo voce de prosseguir por \n esse caminho. Continue onde esta.");
	strcpy (carta[x].certo2, "De repente, uma nuvem de morcegos vira em um corredor e passa por voce ignorando completamente a sua \n presenca. Avance 1 casa.");
	strcpy (carta[x].errado1, "De repente, uma nuvem de morcegos vira em um corredor e passa por voce enquanto conversavam entre si sobre um \n perigo adiante. Continue onde esta.");
	strcpy (carta[x].errado2, "De repente, uma nuvem de morcegos vira em um corredor, mas ao chegar perto de voce, ela para de se mover, \n como se tivesse alcancado seu destino. Volte 1 casa.");
	
	x = 28;// Carta 28
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "LADRAO");
	strcpy (carta[x].dica, "Explorando os corredores do labirinto, voce se depara com uma figura oculta nas sombras, que ao perceber ter sido \n descoberta, declara um assalto: Uma das propriedades para derivar uma funcao diz: Em f(x) = C a funcao derivada sera \n f'(x) = 0, ou seja, quando o valor esta sozinho sem o X ele sera igual a 0.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = 6?\n [1] O f'(x) = 0.\n [2] O f'(x) = 6.\n [3] O f'(x) = 12.\n [4] O f'(x) = 1." );
	strcpy (carta[x].certa, "[1] O f'(x) = 0.");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "Voce, querendo nao ser roubado, empunha suas armas e ameaca o ladrao com o combate, porem, suas palavras nao \n parecem assusta-lo. Continue onde esta.");
	strcpy (carta[x].certo2, "Para evitar qualquer conflito desnecessario, voce oferece uma bolsa de moedas ao ladrao, que, satisfeito, a \n pega e desaparece nas sombras. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce reconhece o ladrao como um amigo de infancia e se aproxima para cumprimenta-lo. Logo, voces comecam a \n relembrar historias do passado juntos. Continue onde esta.");
	strcpy (carta[x].errado2, "Para evitar qualquer conflito desnecessario, voce oferece uma bolsa de moedas ao ladrao, que a pega, mas nao \n se contenta apenas com isso. Volte 1 casa.");
	
	x = 29;// Carta 29
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "ANDARILHO");
	strcpy (carta[x].dica, "Explorando os corredores confusos do labirinto, voce encontra um andarilho perdido no final de um corredor. Para obter \n informacoes, voce se aproxima dele dizendo: Na funcao de 2o grau AX^(2) + BX + C, para calcular o DELTA voce substitui \n os valores de A, B e C na formula B^(2) – 4.A.C, subtraia do quadrado de B, a multiplicacao de -4 por A e por C.");
	strcpy (carta[x].pergunta, "Na funcao 3X^(2) - 6X + 3, qual e o valor do DELTA?\n [1] O valor do DELTA e 0.\n [2] O valor do DELTA e 1.\n [3] O valor do DELTA e 6.\n [4] O valor do DELTA e -6." );
	strcpy (carta[x].certa, "[1] O valor do DELTA e 0.");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "No entanto, o andarilho nao estava perdido, na verdade, estava desenhando um mapa. Ele lhe entrega uma copia, \n mas voce nao consegue entende-lo. Continue onde esta.");
	strcpy (carta[x].certo2, "No entanto, o andarilho nao estava perdido, na verdade, estava desenhando um mapa do labirinto. Ele \n gentilmente lhe entrega uma copia do mapa. Avance 1 casa.");
	strcpy (carta[x].errado1, "No entanto, o andarilho nao estava perdido, na verdade, estava desenhando um mapa. Ele lhe entrega uma copia, \n mas o mapa estava incompleto. Continue onde esta.");
	strcpy (carta[x].errado2, "No entanto, o andarilho estava tao desorientado quanto voce, incapaz de fornecer muitas informacoes sobre \n qual caminho seguir. Volte 1 casa.");
	
	x = 30;// Carta 30
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "SUPORTE");
	strcpy (carta[x].dica, "Caminhando no labirinto, voce escuta gritos desesperados ecoando pelos corredores: Na funcao de 2o grau AX^(2) + BX + C, \n para calcular o DELTA voce substitui os valores de A, B e C na formula B^(2) – 4.A.C, subtraia do quadrado de B, a \n multiplicacao de -4 por A e por C. Seguindo o som, voce encontra uma pessoa presa em uma armadilha.");
	strcpy (carta[x].pergunta, "Na funcao X^(2) - 2X + 1, qual e o valor do DELTA?\n [1] O valor do DELTA e 2.\n [2] O valor do DELTA e 1.\n [3] O valor do DELTA e -2.\n [4] O valor do DELTA e 0." );
	strcpy (carta[x].certa, "[4] O valor do DELTA e 0.");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "Ela estava cercada por varios simbolos magicos, bloqueando sua passagem, sera impossivel para voce com seu \n conhecimento sobre magia liberta-la. Continue onde esta.");
	strcpy (carta[x].certo2, "Ela estava cercada por varias lancas, bloqueando sua passagem, voce facilmente quebra algumas delas, abrindo \n um caminho para escapar da armadilha. Avance 1 casa.");
	strcpy (carta[x].errado1, "Ela estava cercada por varios lasers magicos, voce utiliza seu escudo para conseguir refleti-los, criando uma \n abertura na armadilha. Continue onde esta.");
	strcpy (carta[x].errado2, "Ela estava cercada por varios lasers magicos, bloqueando sua passagem, mas voce nao possui nenhum objeto que \n possa refleti-los para salva-la. Volte 1 casa.");
	
	x = 31;// Carta 31
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "SOBREVIVENCIA");
	strcpy (carta[x].dica, "A medida que avanca mais fundo no labirinto, voce chega a uma sala com o chao repleto de simbolos matematicos: \n AX^(2) + BX + C pode possuir ate duas raizes, para acha-las basta usar a equacao X = ( -B +- RAIZ(DELTA) ) / ( 2 . A ), \n onde voce vai somar ou subtrair o valor negativo de B pela raiz quadrada do DELTA e dividir por duas o valor de A.");
	strcpy (carta[x].pergunta, "Na funcao 2X^(2) - 7X + 6, onde DELTA equivale a 1, quais os valores das raizes?\n [1] Os valores das raizes sao 2,5 e 1,5.\n [2] Os valores das raizes sao 2 e 1,5.\n [3] Os valores das raizes sao 2 e 1.\n [4] Os valores das raizes sao 2,5 e 1." );
	strcpy (carta[x].certa, "[2] Os valores das raizes sao 2 e 1,5.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Ao entrar na sala, a porta atras se fecha e o chao comeca a se mover, embaralhando os simbolos. Voce nao se \n lembra do padrao e nem tenta sair da sala. Continue onde esta.");
	strcpy (carta[x].certo2, "Ao entrar na sala, a porta atras se fecha e o chao comeca a se mover, embaralhando os simbolos. Mas voce se \n lembra do padrao e chega ate o final da sala. Avance 1 casa.");
	strcpy (carta[x].errado1, "Ao entrar na sala, a porta atras se fecha e o chao comeca a se mover, embaralhando os simbolos. \n Instintivamente, voce acerta o caminho. Continue onde esta.");
	strcpy (carta[x].errado2, "Ao entrar na sala, a porta atras se fecha e o chao comeca a se mover, embaralhando os simbolos. Voce nao se \n lembra do padrao e acaba ficando preso na sala. Volte 1 casa.");
	
	x = 32;// Carta 32
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "FURTIVIDADE");
	strcpy (carta[x].dica, "Enquanto explorava os corredores do labirinto, voce sente uma presenca gelida ao seu redor. Progredindo silenciosamente, \n voce avista um fantasma sussurrando: AX^(2) + BX + C pode possuir ate duas raizes, para acha-las basta usar a equacao X = ( -B +- RAIZ(DELTA) ) / ( 2 . A ), onde voce vai somar ou subtrair o valor negativo de B pela raiz quadrada do DELTA \n e dividir por duas o valor de A.");
	strcpy (carta[x].pergunta, "Na funcao 2X^(2) - 4X + 2, onde DELTA equivale a 0, qual o valor da raiz?\n [1] O valor da raiz e 2.\n [2] O valor da raiz e 1.\n [3] O valor da raiz e 4.\n [4] O valor da raiz e 0." );
	strcpy (carta[x].certa, "[2] O valor da raiz e 1.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Equipando seu escudo e espada, voce caminha com cautela, mantendo-se constantemente alerta para um possivel \n combate com o fantasma. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce usa uma estrategia de descrenca, continuando a caminhar como se nao visse nada e atravessando o fantasma \n como se ele nao estivesse la. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce se esconde nas sombras dos corredores, tentando passar despercebido pelo fantasma sem precisar tomar um \n caminho mais longo. Continue onde esta.");
	strcpy (carta[x].errado2, "Apavorado apos seu primeiro encontro com um fantasma, voce rapidamente opta por seguir por outro caminho, \n torcendo para nao ve-lo novamente. Volte 1 casa.");
	
	x = 33;// Carta 33
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "COMERCIANTE");
	strcpy (carta[x].dica, "Entrando no covil dos inimigos, voce descobre uma passagem estreita entre as rochas. Ao se deslocar por ela, voce se \n encontra com um comerciante que sussurrava: Utilizando as propriedades de derivadas \n [f(x) = X^(n) entao f'(x) = n.X^(n-1) e f(x) = C entao f'(x) = 0] podemos fazer derivadas sucessivas, repetindo o \n processo, uma derivada equivale a f'(x), derivar novamente ela resulta em f''(x) e assim sucessivamente.");
	strcpy (carta[x].pergunta, "Qual e o f''(x) derivada da funcao f(x) = X^(4) + X^(5) - 15?\n [1] A f''(x) = 12X^(3) + 20X^(4).\n [2] A f''(x) = 4X^(2) + 5X^(3) + 0.\n [3] A f''(x) = 12X^(2) + 20X^(3).\n [4] A f''(x) = 4X^(3) + 5X^(4) + 15." );
	strcpy (carta[x].certa, "[3] A f''(x) = 12X^(2) + 20X^(3).");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "O comerciante estava se escondendo dos monstros, voce pede desculpas e sai do esconderijo, seguindo em \n direcao as profundezas da caverna. Continue onde esta.");
	strcpy (carta[x].certo2, "O comerciante estava se escondendo dos monstros e propoe que voce se junte a ele, mas voce esta determinado a \n prosseguir com sua missao. Avance 1 casa.");
	strcpy (carta[x].errado1, "O comerciante estava se escondendo dos monstro e voce se propoe e lhe escoltar para fora deste lugar \n perigoso. Continue onde esta.");
	strcpy (carta[x].errado2, "O comerciante estava se escondendo dos monstros e propoe que voce se junte a ele. E voce aceita a \n oportunidade de descansar em um local seguro. Volte 1 casa.");
	
	x = 34;// Carta 34
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "COMBATE");
	strcpy (carta[x].dica, "Dentro do covil inimigo, onde a escuridao parece devorar toda a luz, voce se ve diante de uma clareira, mas seu coracao \n dispara ao ouvir: Utilizando as propriedades de derivadas \n [f(x) = X^(n) entao f'(x) = n.X^(n-1) e f(x) = C entao f'(x) = 0] podemos fazer derivadas sucessivas, repetindo o \n processo, uma derivada equivale a f'(x), derivar novamente ela resulta em f''(x) e assim sucessivamente. Voce nao esta \n sozinho neste lugar.");
	strcpy (carta[x].pergunta, "Qual e o f''(x) derivada da funcao f(x) = X^(4) + X^(3) + 10?\n [1] A f''(x) = 4X^(2) + 3X.\n [2] A f''(x) = 12X^(3) + 6X^(2).\n [3] A f''(x) = 4X^(3) + 3X^(2).\n [4] A f''(x) = 12X^(2) + 6X." );
	strcpy (carta[x].certa, "[4] A f''(x) = 12X^(2) + 6X.");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "Ao se virar, se depara com um imponente Orc pronto para ataca-lo. Esquivando-se habilmente, voce decide nao \n lugar, fugindo pelas sombras. Continue onde esta.");
	strcpy (carta[x].certo2, "Ao se virar, se depara com um imponente Orc pronto para ataca-lo. Esquivando-se habilmente, voce \n contra-ataca, dando inicio a um combate intenso. Avance 1 casa.");
	strcpy (carta[x].errado1, "Ao se virar, se depara com um imponente Orc pronto para ataca-lo. Voce consegue defender com o escudo, mas \n isso da inicio a um intenso combate. Continue onde esta.");
	strcpy (carta[x].errado2, "Ao se virar, se depara com um imponente Orc pronto para ataca-lo. Percebendo o problema, voce foge do combate \n sem olhar para tras. Volte 1 casa.");
	
	x = 35;// Carta 35
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "ANIMAIS");
	strcpy (carta[x].dica, "Se esgueirando pelo covil, voce se depara com um cao infernal. Seus olhos e presas reluzem uma luz ameacadora, enquanto \n ele rosna em sua direcao, voce tenta acalmar o animal: Duas das propriedades para derivar uma funcao dizem: \n Em f(x) = X^(n) a funcao derivada sera f'(x) = n.X^(n-1) e em f(x) = C a funcao derivada sera f'(x) = 0.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = X^(2) + 3X^(3) - 5?\n [1] A f'(x) = X^(2) + 3X^(3) + 0.\n [2] A f'(x) = 2X^(2) + 9X^(3).\n [3] A f'(x) = 2X + 9X^(2).\n [4] A f'(x) = X + 3X^(2) + 0." );
	strcpy (carta[x].certa, "[3] A f'(x) = 2X + 9X^(2).");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "Empunhando seu instrumento, voce toca uma cancao de ninar para a fera. Aos poucos, ela comeca a ficar \n sonolenta, ate finalmente cair em um sono profundo. Continue onde esta.");
	strcpy (carta[x].certo2, "Magicamente voce consegue acalmar o cao infernal, que cessa seus rosnados e abre caminho para que voce \n prossiga. Avance 1 casa.");
	strcpy (carta[x].errado1, "Por meio de suas habilidades voce consegue acalmar o cao infernal, que cessa seus rosnados e abre caminho \n para que voce prossiga. Continue onde esta.");
	strcpy (carta[x].errado2, "Apesar de seus esforcos, o cao infernal salta em sua direcao, ameacando devora-lo. Dominado pelo medo da \n situacao, voce foge em desespero. Volte 1 casa.");
	
	x = 36;// Carta 36
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "LADRAO");
	strcpy (carta[x].dica, "Voce avanca com cautela pelo covil, atento a qualquer sinal de perigo. De repente, voce nota uma figura caida no chao. \n Ao se aproximar, ela desaparece e reaparece atras de voce, sussurrando: Em f(x) = X^(n) a funcao derivada sera \n f'(x) = n.X^(n-1) e em f(x) = C a funcao derivada sera f'(x) = 0.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = 2X^(2) + 2X^(3) + 6?\n [1] A f'(x) = 4X + 6X^(2).\n [2] A f'(x) = 4X^(2) + 6X^(4) + 0.\n [3] A f'(x) = 2X^(2) + 2X^(3).\n [4] A f'(x) = 2X + 2X^(2) + 0." );
	strcpy (carta[x].certa, "[1] A f'(x) = 4X + 6X^(2).");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "Voce saca sua arma e assume uma posicao defensiva, mas o ladrao ri da situacao e avanca para o combate, \n tentando roubar seus pertences. Continue onde esta.");
	strcpy (carta[x].certo2, "Voce tenta negociar com o ladrao, persuadindo-o a nao levar tudo. Entregando algumas moedas, ele concorda e \n voce continua a avancar pelo Covil Sem Limites. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce ri do ladrao e, com um movimento furtivo, se move rapidamente para suas costas, fazendo ele fugir com \n medo, arrependido do que tentou fazer. Continue onde esta.");
	strcpy (carta[x].errado2, "Voce tenta negociar com o ladrao, mas ele nao esta interessado em barganhar. Em um movimento rapido, ele \n rouba seus pertences e desaparece nas sombras. Volte 1 casa.");
	
	x = 37;// Carta 37
	carta[x].vantagem = 2;
	carta[x].desvantagem = 1;
	strcpy (carta[x].tipo, "ANDARILHO");
	strcpy (carta[x].dica, "Na escuridao do Covil Sem Limites, enquanto caminhava voce se depara com um andarilho cujos passos, nao emitem som \n algum. Ao notar sua presenca, ele o cumprimenta gentilmente: Em f(x) = X^(n) a funcao derivada sera f'(x) = n.X^(n-1) e \n em f(x) = C a funcao derivada sera f'(x) = 0.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = 4X^(3) + X^(4) - 3?\n [1] A f'(x) = 4X^(2) + X^(3).\n [2] A f'(x) = 12X^(2) + 4X^(3).\n [3] A f'(x) = 4X^(2) + X^(3) - 3.\n [4] A f'(x) = 12X^(2) + 4X^(3) - 3." );
	strcpy (carta[x].certa, "[2] A f'(x) = 12X^(2) + 4X^(3).");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, "Desconfiado dessa pessoa misteriosa, voce se transforma em um morcego e se esconde nas sombras da caverna. \n Continue onde esta.");
	strcpy (carta[x].certo2, "O andarilho se revelou uma boa pessoa, alertando-o sobre os perigos adiante e fornecendo instrucoes sobre os \n melhores caminhos a seguir. Avance 1 casa.");
	strcpy (carta[x].errado1, "O andarilho percebeu seu gosto musical e compartilhou contos de misterios e aventuras deste lugar, na \n esperanca de inspira-lo. Continue onde esta.");
	strcpy (carta[x].errado2, "O andarilho se revelou uma pessoa muito misteriosa, alertando-o sobre os perigos adiante por meio de enigmas \n e charadas. Volte 1 casa.");
	
	x = 38;// Carta 38
	carta[x].vantagem = 3;
	carta[x].desvantagem = 4;
	strcpy (carta[x].tipo, "SUPORTE");
	strcpy (carta[x].dica, "Em um canto oculto do covil, voce descobre uma cela e, acreditando ter encontrado a princesa voce corre para liberta-la. \n No entanto, ao se aproximar, uma aldea suplica por socorro: Em f(x) = X^(n) a funcao derivada sera f'(x) = n.X^(n-1) e \n em f(x) = C a funcao derivada sera f'(x) = 0");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = 2X^(5) + 2X^(4) - 7?\n [1] A f'(x) = 10X^(4) + 8X^(3).\n [2] A f'(x) = 2X^(4) + 2X^(3).\n [3] A f'(x) = 2X^(4) + 2X^(3) - 7.\n [4] A f'(x) = 10X^(4) + 8X^(3) - 7." );
	strcpy (carta[x].certa, "[1] A f'(x) = 10X^(4) + 8X^(3).");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, "Apos examinar a porta da cela, voce descobre que nao sera possivel abri-la, voce informa ela que nao sera \n possivel liberta-la. Continue onde esta.");
	strcpy (carta[x].certo2, "Apos examinar a porta da cela, voce descobre uma maneira de abri-la, mas diz que nao podera acompanha-la, \n pois precisa continuar sua busca pela princesa. Avance 1 casa.");
	strcpy (carta[x].errado1, "Apos examinar a porta da cela, voce descobre uma maneira de abri-la e se dispoe a escolta-la ate o lado de \n fora do Covil Sem Limites. Continue onde esta.");
	strcpy (carta[x].errado2, "Apos examinar a porta da cela, voce descobre que nao sera possivel abri-la, mas promete a ela que ira voltar \n com ajuda. Volte 1 casa.");
	
	x = 39;// Carta 39
	carta[x].vantagem = 1;
	carta[x].desvantagem = 2;
	strcpy (carta[x].tipo, "SOBREVIVENCIA");
	strcpy (carta[x].dica, "Andando pela escuridao do covil, voce escorrega em uma rocha coberta de musgo e cai, fazendo um barulho. Internamente, \n voce reflete: Em f(x) = X^(n) a funcao derivada sera f'(x) = n.X^(n-1) e em f(x) = C a funcao derivada sera f'(x) = 0. O \n estrondo causado por sua queda desencadeia um desmoronamento acima de voce.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = 3X^(6) + 2X^(5) + 11?\n [1] A f'(x) = 18X^(5) + 10X^(4) + 11.\n [2] A f'(x) = 3X^(5) + 2X^(4) + 11.\n [3] A f'(x) = 3X^(5) + 2X^(4).\n [4] A f'(x) = 18X^(5) + 10X^(4)." );
	strcpy (carta[x].certa, "[4] A f'(x) = 18X^(5) + 10X^(4).");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, "Instintivamente voce rola para tras, na sua frente so e possivel ver rochas e poeira, tera que achar outro \n caminho para seguir adiante. Continue onde esta.");
	strcpy (carta[x].certo2, "Habilmente voce rola para a frente, ficando preso pelas rochas e poeira, tera que achar outro caminho para \n sair do covil. Avance 1 casa.");
	strcpy (carta[x].errado1, "Habilmente voce se levanta e salta para a frente, ficando preso pelas rochas e poeira, tera que achar outro \n caminho para sair do covil. Continue onde esta.");
	strcpy (carta[x].errado2, "Instintivamente voce se levanta e salta para tras, na sua frente so e possivel ver rochas e poeira, tera que \n achar outro caminho para seguir adiante. Volte 1 casa.");
	
	x = 40;// Carta 40
	carta[x].vantagem = 4;
	carta[x].desvantagem = 3;
	strcpy (carta[x].tipo, "FURTIVIDADE");
	strcpy (carta[x].dica, "Se aproximando ao fim do Covil Sem Limites, proximo a uma ponte de ossos, voce observa um Lich amedrontador dando ordem \n aos seus servos esqueletos: Em f(x) = X^(n) a funcao derivada sera f'(x) = n.X^(n-1) e em f(x) = C a funcao derivada \n sera f'(x) = 0.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = 2X^(6) + 3X^(4) - 8?\n [1] A f'(x) = 2X^(5) + 3X^(3) – 8.\n [2] A f'(x) = 12X^(5) + 12X^(3) – 8.\n [3] A f'(x) = 12X^(5) + 12X^(3).\n [4] A f'(x) = 2X^(5) + 3X^(3)." );
	strcpy (carta[x].certa, "[3] A f'(x) = 12X^(5) + 12X^(3).");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, "Diante deste desafio, voce atrai a atencao dos monstros e os conduz pelos corredores estreitos da caverna, \n onde podera derrota-los um por um. Continue onde esta.");
	strcpy (carta[x].certo2, "Enfrentando esse perigo iminente, voce opta por contornar cuidadosamente os monstros, evitando chamar a \n atencao deles para si. Avance 1 casa.");
	strcpy (carta[x].errado1, "Voce utiliza todas as suas habilidades furtivas para se ocultar nas sombras da caverna, aguardando que o \n inimigo se afaste do caminho. Continue onde esta.");
	strcpy (carta[x].errado2, "Enfrentando esse perigo iminente, voce decide procurar outro caminho em vez de arriscar enfrentar esses \n monstros assustadores. Volte 1 casa.");
	
	x = 41;// Carta 41
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "FINALIZACAO");
	strcpy (carta[x].dica, "Nas profundezas do Covil Sem Limites, atravessando por uma ponte de ossos sobre um lago de acido, Dentro de \n uma cela escura e umida, voce encontra a princesa de Calcularia, envolta em lagrimas silenciosas enquanto \n esta encostada na parede. Assim que seus olhares se cruzam, a expressao da princesa se ilumina com um sorriso \n radiante de esperanca. Ela te suplica em um sussurro desesperado para salva-la.");
	strcpy (carta[x].pergunta, "Qual e o f'(x) derivada da funcao f(x) = 2X^(5) + 3X^(6) - 7?\n [1] A f'(x) = 10X^(4) + 18x^(5).\n [2] A f'(x) = 2X^(4) + 3X^(5) - 7.\n [3] A f'(x) = 10X^(5) + 18x^(6).\n [4] A f'(x) = 2X^(5) + 3x^(6) - 7." );
	strcpy (carta[x].certa, "[1] A f'(x) = 10X^(4) + 18x^(5).");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Com destreza e precisao, voce consegue abrir o \n cadeado, libertando a princesa. Em um gesto de profundo agradecimento, ela o abraca calorosamente. Juntos, \n voces escapam do Covil Sem Limites e vivenciam uma jornada de volta para o reino de Calcularia, onde voce e \n parabenizado por todos pelo seu grande feito. Voce Venceu o Jogo.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Ao tentar abri-lo, um ruido estrondoso ecoa pelo \n Covil Sem Limites, alertando os monstros que guardam o local de sua presenca. Consciente de que a seguranca \n da princesa esta em jogo, voce decide recuar, prometendo a ela que voltara em breve. Volte 4 casas.");
	
	x = 42;// Carta 42
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "FINALIZACAO");
	strcpy (carta[x].dica, "Nas profundezas do Covil Sem Limites, atravessando por uma ponte de ossos sobre um lago de acido, Dentro de \n uma cela escura e umida, voce encontra a princesa de Calcularia, envolta em lagrimas silenciosas enquanto \n esta encostada na parede. Assim que seus olhares se cruzam, a expressao da princesa se ilumina com um sorriso \n radiante de esperanca. Ela te suplica em um sussurro desesperado para salva-la.");
	strcpy (carta[x].pergunta, "Qual e o f''(x) derivada da funcao f(x) = 2X^(4) + 2X^(5) - 21?\n [1] A f''(x) = 8X^(3) + 10X^(4).\n [2] A f''(x) = 24X^(2) + 40X^(3).\n [3] A f''(x) = 2X^(4) + 2X^(5).\n [4] A f''(x) = 38X^(1) + 120X^(2)." );
	strcpy (carta[x].certa, "[2] A f''(x) = 24X^(2) + 40X^(3).");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Com destreza e precisao, voce consegue abrir o \n cadeado, libertando a princesa. Em um gesto de profundo agradecimento, ela o abraca calorosamente. Juntos, \n voces escapam do Covil Sem Limites e vivenciam uma jornada de volta para o reino de Calcularia, onde voce e \n parabenizado por todos pelo seu grande feito. Voce Venceu o Jogo.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Ao tentar abri-lo, um ruido estrondoso ecoa pelo \n Covil Sem Limites, alertando os monstros que guardam o local de sua presenca. Consciente de que a seguranca \n da princesa esta em jogo, voce decide recuar, prometendo a ela que voltara em breve. Volte 4 casas.");
	
	x = 43;// Carta 43
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "FINALIZACAO");
	strcpy (carta[x].dica, "Nas profundezas do Covil Sem Limites, atravessando por uma ponte de ossos sobre um lago de acido, Dentro de \n uma cela escura e umida, voce encontra a princesa de Calcularia, envolta em lagrimas silenciosas enquanto \n esta encostada na parede. Assim que seus olhares se cruzam, a expressao da princesa se ilumina com um sorriso \n radiante de esperanca. Ela te suplica em um sussurro desesperado para salva-la.");
	strcpy (carta[x].pergunta, "Na funcao 2X^(2) + 4X + 2, onde DELTA equivale a 0, qual o valor da raiz?\n [1] A raiz da funcao e 1.\n [2] A raiz da funcao e 0.\n [3] A raiz da funcao e -1.\n [4] A raiz da funcao e -2." );
	strcpy (carta[x].certa, "[3] A raiz da funcao e -1");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Com destreza e precisao, voce consegue abrir o \n cadeado, libertando a princesa. Em um gesto de profundo agradecimento, ela o abraca calorosamente. Juntos, \n voces escapam do Covil Sem Limites e vivenciam uma jornada de volta para o reino de Calcularia, onde voce e \n parabenizado por todos pelo seu grande feito. Voce Venceu o Jogo.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Ao tentar abri-lo, um ruido estrondoso ecoa pelo \n Covil Sem Limites, alertando os monstros que guardam o local de sua presenca. Consciente de que a seguranca \n da princesa esta em jogo, voce decide recuar, prometendo a ela que voltara em breve. Volte 4 casas.");
	
	x = 44;// Carta 44
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "FINALIZACAO");
	strcpy (carta[x].dica, "Nas profundezas do Covil Sem Limites, atravessando por uma ponte de ossos sobre um lago de acido, Dentro de \n uma cela escura e umida, voce encontra a princesa de Calcularia, envolta em lagrimas silenciosas enquanto \n esta encostada na parede. Assim que seus olhares se cruzam, a expressao da princesa se ilumina com um sorriso \n radiante de esperanca. Ela te suplica em um sussurro desesperado para salva-la.");
	strcpy (carta[x].pergunta, "Na funcao X^(2) - 4X - 2, qual e o valor do DELTA?\n [1] O valor de DELTA e 21.\n [2] O valor de DELTA e 22.\n [3] O valor de DELTA e 23.\n [4] O valor de DELTA e 24." );
	strcpy (carta[x].certa, "[4] O valor de DELTA e 24.");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Com destreza e precisao, voce consegue abrir o \n cadeado, libertando a princesa. Em um gesto de profundo agradecimento, ela o abraca calorosamente. Juntos, \n voces escapam do Covil Sem Limites e vivenciam uma jornada de volta para o reino de Calcularia, onde voce e \n parabenizado por todos pelo seu grande feito. Voce Venceu o Jogo.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Ao tentar abri-lo, um ruido estrondoso ecoa pelo \n Covil Sem Limites, alertando os monstros que guardam o local de sua presenca. Consciente de que a seguranca \n da princesa esta em jogo, voce decide recuar, prometendo a ela que voltara em breve. Volte 4 casas.");
	
	x = 45;// Carta 45
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "FINALIZACAO");
	strcpy (carta[x].dica, "Nas profundezas do Covil Sem Limites, atravessando por uma ponte de ossos sobre um lago de acido, Dentro de \n uma cela escura e umida, voce encontra a princesa de Calcularia, envolta em lagrimas silenciosas enquanto \n esta encostada na parede. Assim que seus olhares se cruzam, a expressao da princesa se ilumina com um sorriso \n radiante de esperanca. Ela te suplica em um sussurro desesperado para salva-la.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao X^(2) + 3X - 10, quando X for 5?\n [1] O f(x) = 30.\n [2] O f(x) = 35.\n [3] O f(x) = 40.\n [4] O f(x) = 25." );
	strcpy (carta[x].certa, "[1] O f(x) = 30.");
	carta[x].resposta = 1;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Com destreza e precisao, voce consegue abrir o \n cadeado, libertando a princesa. Em um gesto de profundo agradecimento, ela o abraca calorosamente. Juntos, \n voces escapam do Covil Sem Limites e vivenciam uma jornada de volta para o reino de Calcularia, onde voce e \n parabenizado por todos pelo seu grande feito. Voce Venceu o Jogo.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Ao tentar abri-lo, um ruido estrondoso ecoa pelo \n Covil Sem Limites, alertando os monstros que guardam o local de sua presenca. Consciente de que a seguranca \n da princesa esta em jogo, voce decide recuar, prometendo a ela que voltara em breve. Volte 4 casas.");
	
	x = 46;// Carta 46
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "FINALIZACAO");
	strcpy (carta[x].dica, "Nas profundezas do Covil Sem Limites, atravessando por uma ponte de ossos sobre um lago de acido, Dentro de \n uma cela escura e umida, voce encontra a princesa de Calcularia, envolta em lagrimas silenciosas enquanto \n esta encostada na parede. Assim que seus olhares se cruzam, a expressao da princesa se ilumina com um sorriso \n radiante de esperanca. Ela te suplica em um sussurro desesperado para salva-la.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao 6X/2, quando X for 3?\n [1] O f(x) = 3.\n [2] O f(x) = 9.\n [3] O f(x) = 18.\n [4] O f(x) = 12." );
	strcpy (carta[x].certa, "[2] O f(x) = 9.");
	carta[x].resposta = 2;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Com destreza e precisao, voce consegue abrir o \n cadeado, libertando a princesa. Em um gesto de profundo agradecimento, ela o abraca calorosamente. Juntos, \n voces escapam do Covil Sem Limites e vivenciam uma jornada de volta para o reino de Calcularia, onde voce e \n parabenizado por todos pelo seu grande feito. Voce Venceu o Jogo.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Ao tentar abri-lo, um ruido estrondoso ecoa pelo \n Covil Sem Limites, alertando os monstros que guardam o local de sua presenca. Consciente de que a seguranca \n da princesa esta em jogo, voce decide recuar, prometendo a ela que voltara em breve. Volte 4 casas.");
	
	x = 47;// Carta 47
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "FINALIZACAO");
	strcpy (carta[x].dica, "Nas profundezas do Covil Sem Limites, atravessando por uma ponte de ossos sobre um lago de acido, Dentro de \n uma cela escura e umida, voce encontra a princesa de Calcularia, envolta em lagrimas silenciosas enquanto \n esta encostada na parede. Assim que seus olhares se cruzam, a expressao da princesa se ilumina com um sorriso \n radiante de esperanca. Ela te suplica em um sussurro desesperado para salva-la.");
	strcpy (carta[x].pergunta, "Na funcao 3X-21, qual e a sua raiz?\n [1] A raiz da funcao e -7.\n [2] A raiz da funcao e 24.\n [3] A raiz da funcao e 7.\n [4] A raiz da funcao e 18." );
	strcpy (carta[x].certa, "[3] A raiz da funcao e 7.");
	carta[x].resposta = 3;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Com destreza e precisao, voce consegue abrir o \n cadeado, libertando a princesa. Em um gesto de profundo agradecimento, ela o abraca calorosamente. Juntos, \n voces escapam do Covil Sem Limites e vivenciam uma jornada de volta para o reino de Calcularia, onde voce e \n parabenizado por todos pelo seu grande feito. Voce Venceu o Jogo.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Ao tentar abri-lo, um ruido estrondoso ecoa pelo \n Covil Sem Limites, alertando os monstros que guardam o local de sua presenca. Consciente de que a seguranca \n da princesa esta em jogo, voce decide recuar, prometendo a ela que voltara em breve. Volte 4 casas.");
			
	x = 48;// Carta 48
	carta[x].vantagem = 0;
	carta[x].desvantagem = 0;
	strcpy (carta[x].tipo, "FINALIZACAO");
	strcpy (carta[x].dica, "Nas profundezas do Covil Sem Limites, atravessando por uma ponte de ossos sobre um lago de acido, Dentro de \n uma cela escura e umida, voce encontra a princesa de Calcularia, envolta em lagrimas silenciosas enquanto \n esta encostada na parede. Assim que seus olhares se cruzam, a expressao da princesa se ilumina com um sorriso \n radiante de esperanca. Ela te suplica em um sussurro desesperado para salva-la.");
	strcpy (carta[x].pergunta, "Qual e o f(x) da funcao 4X+2, quando X for 7?\n [1] O f(x) = 13.\n [2] O f(x) = 26.\n [3] O f(x) = 28.\n [4] O f(x) = 30." );
	strcpy (carta[x].certa, "[4] .");
	carta[x].resposta = 4;
	strcpy (carta[x].certo1, ". Continue onde esta.");
	strcpy (carta[x].certo2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Com destreza e precisao, voce consegue abrir o \n cadeado, libertando a princesa. Em um gesto de profundo agradecimento, ela o abraca calorosamente. Juntos, \n voces escapam do Covil Sem Limites e vivenciam uma jornada de volta para o reino de Calcularia, onde voce e \n parabenizado por todos pelo seu grande feito. Voce Venceu o Jogo.");
	strcpy (carta[x].errado1, ". Continue onde esta.");
	strcpy (carta[x].errado2, "Ao examinar a porta da cela, voce nota um imponente cadeado. Ao tentar abri-lo, um ruido estrondoso ecoa pelo \n Covil Sem Limites, alertando os monstros que guardam o local de sua presenca. Consciente de que a seguranca \n da princesa esta em jogo, voce decide recuar, prometendo a ela que voltara em breve. Volte 4 casas.");

	return 0;
}